name: ecommerce_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  change_app_package_name: ^1.1.0
#  ------------------------------firabase----------------------
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_analytics: ^10.4.4
  firebase_storage: ^11.2.5
#  ------------------------------provider----------------------
  provider: ^6.0.5
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.4
#  ------------------------------helper package----------------------
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  zoom_tap_animation: ^1.1.0
  fluttertoast: ^8.2.2
  image_picker: ^1.0.1
  shimmer: ^3.0.0
  like_button: ^2.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
